import {useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {Eye,EyeOff,ArrowRight,GraduationCap} from 'lucide-react';
import {Brand,Field,ErrorMessage} from '../components/UI';
import {login,register} from '../services/storage';
export default function Auth({registering=false,onAuth}){
 const [show,setShow]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);const navigate=useNavigate();
 async function submit(e){e.preventDefault();setError('');const data=new FormData(e.currentTarget); const password=data.get('password');if(registering && password!==data.get('confirm')){setError('Your passwords do not match.');return;}setBusy(true);try{const user=registering?await register(data.get('name'),data.get('email'),password):await login(data.get('email'),password);onAuth(user);navigate('/');}catch(err){setError(err.message);}finally{setBusy(false);}}
 return <div className="auth-shell"><Brand/><div className="auth-art"><GraduationCap size={64} strokeWidth={1}/><span>SMALL STEPS. BIG FUTURES.</span></div><h1>{registering?'Make room for growth.':'Welcome back.'}</h1><p className="muted">{registering?'Your academic journey, beautifully organized.':'A little clarity for your next big goal.'}</p><form onSubmit={submit}>{registering&&<Field label="Full name"><input name="name" autoComplete="name" required maxLength={80} pattern=".*\S.*" placeholder="Your full name"/></Field>}<Field label="Email address"><input name="email" type="email" autoComplete="email" required placeholder="you@university.edu"/></Field><Field label="Password"><div className="password"><input name="password" type={show?'text':'password'} autoComplete={registering?'new-password':'current-password'} minLength={8} required placeholder="At least 8 characters"/><button type="button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></Field>{registering&&<Field label="Confirm password"><input name="confirm" type={show?'text':'password'} autoComplete="new-password" minLength={8} required placeholder="Re-enter your password"/></Field>}<ErrorMessage message={error}/><button className="primary wide" disabled={busy}>{busy?'Just a moment?':registering?'Create account':'Sign in'}<ArrowRight size={18}/></button></form><p className="auth-switch">{registering?'Already have an account?':"Don?t have an account?"} <Link to={registering?'/login':'/register'}>{registering?'Sign in':'Create account'}</Link></p><p className="footnote">Local demo authentication. Your account and grades stay in this browser. This is not production-grade authentication.</p></div>
}
