import {useState} from 'react';
import {useNavigate,useParams} from 'react-router-dom';
import {Plus,Trash2,Check,ArrowRight} from 'lucide-react';
import {Heading,Field,ErrorMessage} from '../components/UI';
import {totals,formatGpa} from '../utils/calculations';
const subject=()=>({id:crypto.randomUUID(),name:'',credits:'3',grade:'A'});
export default function Calculator({academic}){const {id}=useParams();const existing=academic.semesters.find(s=>s.id===id);const [name,setName]=useState(existing?.name||''),[subjects,setSubjects]=useState(existing?.subjects||[subject(),subject(),subject()]),[result,setResult]=useState(null),[error,setError]=useState('');const navigate=useNavigate();
const change=(sid,key,value)=>{setSubjects(subjects.map(s=>s.id===sid?{...s,[key]:value}:s));setResult(null);};
function calculate(e){e.preventDefault();setError('');if(!subjects.length){setError('Add at least one subject.');return;}const courses=subjects.map(s=>({...s,name:s.name.trim(),credits:Number(s.credits),points:academic.scale[s.grade]}));if(!name.trim()||courses.some(s=>!s.name||!Number.isFinite(s.credits)||s.credits<=0)){setError('Give your semester and subjects names, with positive credits.');return;}setResult({courses,...totals([{subjects:courses}])});}
function save(){try{academic.save({id:existing?.id||crypto.randomUUID(),name:name.trim(),subjects:result.courses,updatedAt:new Date().toISOString()});navigate('/history');}catch(e){setError(e.message);}}
return <><Heading eyebrow="MAKE EVERY CREDIT COUNT" title={existing?'Edit semester.':'GPA calculator.'}>Build your semester, one subject at a time.</Heading>{id&&!existing?<ErrorMessage message="This semester could not be found."/>:<><form onSubmit={calculate}><Field label="Semester name"><input value={name} onChange={e=>{setName(e.target.value);setResult(null);}} required maxLength={80} placeholder="e.g. Semester 01"/></Field><div className="section-heading"><h2>Subjects</h2><span className="muted">{subjects.length.toString().padStart(2,'0')} added</span></div><div className="subjects">{subjects.map((s,i)=><section className="subject-card" key={s.id}><div className="subject-heading"><span className="eyebrow">SUBJECT {String(i+1).padStart(2,'0')}</span><button type="button" className="icon-button" aria-label={`Delete subject ${i+1}`} onClick={()=>{setSubjects(subjects.filter(c=>c.id!==s.id));setResult(null);}}><Trash2 size={17}/></button></div><Field label="Subject name"><input required maxLength={100} value={s.name} onChange={e=>change(s.id,'name',e.target.value)} placeholder="e.g. Advanced Algorithms"/></Field><div className="two-columns"><Field label="Credits"><input type="number" min="0.1" max="100" step="0.1" required value={s.credits} onChange={e=>change(s.id,'credits',e.target.value)}/></Field><Field label="Grade"><select value={s.grade} onChange={e=>change(s.id,'grade',e.target.value)}>{Object.entries(academic.scale).map(([g,p])=><option key={g} value={g}>{g} ? {p.toFixed(1)}</option>)}</select></Field></div></section>)}</div><button type="button" className="wide dashed" onClick={()=>{setSubjects([...subjects,subject()]);setResult(null);}}><Plus size={17}/>Add subject</button><p className="footnote">Using your configured 4.0 scale. Grading scales vary by institution. Adjust grade points in Profile.</p><ErrorMessage message={error}/><button className="primary wide" type="submit">Calculate GPA <ArrowRight size={18}/></button></form>{result&&<section className="result" aria-live="polite"><span className="eyebrow">SEMESTER GPA</span><div className="gpa-number">{formatGpa(result.gpa)}<span>/ 4.00</span></div><p className="muted">{result.credits} credits across {result.courses.length} subjects</p><button className="primary wide" onClick={save}><Check size={18}/>Save semester</button></section>}</>}</>}
