import {useEffect,useRef} from 'react';
import {ArrowUpRight, GraduationCap} from 'lucide-react';
import {Link} from 'react-router-dom';
export function Brand(){return <div className="brand"><span className="brand-icon"><GraduationCap size={23}/></span>GradeFlow<span className="brand-dot">?</span></div>}
export function Heading({eyebrow,title,children}){return <header className="page-heading"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{children && <p className="muted">{children}</p>}</header>}
export function Empty({title='Your journey starts here',text='Add your first semester to see your academic progress.'}){return <div className="empty"><GraduationCap size={36}/><h3>{title}</h3><p>{text}</p><Link className="button primary" to="/calculator">Add your first semester <ArrowUpRight size={17}/></Link></div>}
export function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
export function ErrorMessage({message}){return message?<p role="alert" className="error">{message}</p>:null}
export function Confirm({title,text,onCancel,onConfirm}){const ref=useRef(null);useEffect(()=>{const previous=document.activeElement;ref.current?.querySelector('button')?.focus();return()=>previous?.focus();},[]);function keyboard(e){if(e.key==='Escape')onCancel();if(e.key==='Tab'){const buttons=ref.current.querySelectorAll('button');if(e.shiftKey&&document.activeElement===buttons[0]){e.preventDefault();buttons[buttons.length-1].focus();}else if(!e.shiftKey&&document.activeElement===buttons[buttons.length-1]){e.preventDefault();buttons[0].focus();}}}return <div className="modal-backdrop"><section ref={ref} onKeyDown={keyboard} className="modal" role="alertdialog" aria-modal="true" aria-labelledby="confirm-title"><h2 id="confirm-title">{title}</h2><p className="muted">{text}</p><div className="actions"><button autoFocus onClick={onCancel}>Cancel</button><button className="primary" onClick={onConfirm}>Confirm deletion</button></div></section></div>}
